ENV some=.env.staging

FROM node:8-alpine as build-stage
WORKDIR /app
COPY ./inex_frontend/package*.json /app/
RUN npm config set registry http://registry.npmjs.org/
RUN npm set progress=true
RUN npm update
COPY ./inex_frontend /app/
RUN cp $some .env
RUN npm run build

FROM nginx:1.13

COPY --from=build-stage /app/dist /home/frontend/build
COPY ./docker/nginx/sites-enabled-front /etc/nginx/conf.d/default.conf

EXPOSE 80