version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APP_PATH_HOST_BACK}:${APP_PATH_CONTAINER_BACK}
      - ${SITES_ENABLED_HOST_BACK}:${SITES_ENABLED_CONTAINER_BACK}
    depends_on:
      - php

  php:
    build:
      context: ./inex_backend
      dockerfile: Dockerfile_dev
    image: fpm_7.2:latest
    volumes:
      - ${APP_PATH_HOST_BACK}:${APP_PATH_CONTAINER_BACK}
      - ./php/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: inex
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - ../db_volume:/var/lib/mysql
    ports:
      - "3306:3306"


#  react:
#    image: nginx:1.13
#    ports:
#      - ${REACT_PORT}:443
#    volumes:
#      - ./build:/home/frontend/build
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./sites-enabled-front:/etc/nginx/conf.d/front.conf

  composer:
    image: composer:1.7.2
    volumes:
          - ${APP_PATH_HOST_BACK}:${APP_PATH_CONTAINER_BACK}
    working_dir: ${APP_PATH_CONTAINER_BACK}
    command: composer update

  inex_front:
    image: node:8-alpine
    ports:
          - ${REACT_PORT}:3001
    volumes:
      - ${APP_PATH_HOST_FRONT}:${APP_PATH_CONTAINER_FRONT}
    working_dir: ${APP_PATH_CONTAINER_FRONT}
    command: [sh, -c, "npm install && npm start"]
